'use strict';
// 変換ルール
// day: 月=1, 火=2, 水=3, 木=4, 金=5, 土=6
// period: 3.4 → 34, 4.5 → 45
// consecutiveFlag: 例 "■木4.5" → "木45"、空欄 → ""
// required: 0=なし, 1=選択必修, 2=必修
// style: 0=対面, 1=オンライン

const SD = [
	{
    day: 1,
    period: 1,
    term: "AB",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "スポーツ総合演習（SD・春）",
    teacher: "佐藤 優希",
    room: "市ヶ谷体育",
    style: 0,
  },
  {
    day: 1,
    period: 2,
    term: "AB",
    consecutiveFlag: "水5",
    required: 2,
    minGrade: 3,
    maxGrade: 3,
    name: "ゼミナール1",
    teacher: "SEONG YOUNG AH",
    room: "SDスタジオ他",
    style: 0,
  },
  {
    day: 1,
    period: 34,
    term: "AB",
    consecutiveFlag: "",
    required: 2,
    minGrade: 3,
    maxGrade: 3,
    name: "プロジェクト実習・制作1",
    teacher: "SEONG YOUNG AH",
    room: "SDスタジオ他",
    style: 0,
  },
  {
    day: 1,
    period: 34,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "エンジニアリングCAD演習X",
    teacher: "黒田 克史",
    room: "情報教室2",
    style: 0,
  },
  {
    day: 1,
    period: 34,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "エンジニアリングCAD演習Y",
    teacher: "駒井 悠亮",
    room: "情報教室1",
    style: 0,
  },
  {
    day: 1,
    period: 4,
    term: "AB",
    consecutiveFlag: "",
    required: 0,
    minGrade: 3,
    maxGrade: 4,
    name: "ランドスケープデザイン",
    teacher: "大木 一",
    room: "都市スタジオルーム",
    style: 0,
  },
  {
    day: 1,
    period: 5,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 4,
    maxGrade: 4,
    name: "応用プロジェクト1",
    teacher: "岩月 正見",
    room: "SDスタジオ",
    style: 0,
  },
  {
    day: 1,
    period: 45,
    term: "A",
    consecutiveFlag: "木45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語1",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 56,
    term: "A",
    consecutiveFlag: "木56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語1（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 12,
    term: "B",
    consecutiveFlag: "",
    required: 0,
    minGrade: 2,
    maxGrade: 4,
    name: "地図とGIS",
    teacher: "今井 龍一",
    room: "T413",
    style: 0,
  },
  {
    day: 1,
    period: 45,
    term: "B",
    consecutiveFlag: "木45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語2",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 56,
    term: "B",
    consecutiveFlag: "木56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語2（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 1,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "スポーツ総合演習（SD・秋）",
    teacher: "佐藤 優希",
    room: "市ヶ谷体育",
    style: 0,
  },
  {
    day: 1,
    period: 12,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "メディアデザイン演習",
    teacher: "大西 景太",
    room: "情報教室1,情報教室2",
    style: 0,
  },
  {
    day: 1,
    period: 2,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "中国語・中国文化（SD）",
    teacher: "田村 広子",
    room: "T511",
    style: 0,
  },
  {
    day: 1,
    period: 2,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "エンジニアリングデザインの応用",
    teacher: "宮田 雄二郎",
    room: "T414",
    style: 0,
  },
  {
    day: 1,
    period: 3,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "医療福祉工学",
    teacher: "川瀬 利弘",
    room: "T313",
    style: 1,
  },
  {
    day: 1,
    period: 34,
    term: "CD",
    consecutiveFlag: "水34",
    required: 2,
    minGrade: 3,
    maxGrade: 3,
    name: "プロジェクト実習・制作2",
    teacher: "SEONG YOUNG AH",
    room: "SDスタジオ他",
    style: 0,
  },
  {
    day: 1,
    period: 34,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "インダストリアルデザイン実習",
    teacher: "安積 伸",
    room: "T511",
    style: 0,
  },
  {
    day: 1,
    period: 45,
    term: "C",
    consecutiveFlag: "木45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語3",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 56,
    term: "C",
    consecutiveFlag: "木56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語3（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 45,
    term: "D",
    consecutiveFlag: "木45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語4",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 56,
    term: "D",
    consecutiveFlag: "木56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語4（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 1,
    period: 56,
    term: "D",
    consecutiveFlag: "",
    required: 0,
    minGrade: 3,
    maxGrade: 4,
    name: "文明と資源",
    teacher: "網野 禎昭",
    room: "その他",
    style: 1,
  },
  {
    day: 2,
    period: 12,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "基礎デザイン制作X",
    teacher: "土屋 雅人",
    room: "SDスタジオ",
    style: 0,
  },
  {
    day: 2,
    period: 2,
    term: "AB",
    consecutiveFlag: "",
    required: 0,
    minGrade: 2,
    maxGrade: 4,
    name: "環境工学",
    teacher: "中野 淳太",
    room: "マルチメディアホール",
    style: 0,
  },
  {
    day: 2,
    period: 3,
    term: "AB",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "環境とエネルギー（建築・SD）",
    teacher: "下田 昭郎",
    room: "T412",
    style: 0,
  },
  {
    day: 2,
    period: 4,
    term: "AB",
    consecutiveFlag: "",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "技術者倫理（SD）",
    teacher: "池田 尚司",
    room: "T511",
    style: 0,
  },
  {
    day: 2,
    period: 12,
    term: "A",
    consecutiveFlag: "",
    required: 0,
    minGrade: 3,
    maxGrade: 4,
    name: "都市デザイン",
    teacher: "上山 肇",
    room: "都市スタジオ",
    style: 0,
  },
  {
    day: 2,
    period: 12,
    term: "A",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "ビジネスモデルデザイン",
    teacher: "姜 理惠",
    room: "T412",
    style: 0,
  },
  {
    day: 2,
    period: 12,
    term: "A",
    consecutiveFlag: "",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "微分積分学Y",
    teacher: "山田 泰之",
    room: "T312",
    style: 0,
  },
  {
    day: 2,
    period: 34,
    term: "A",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "コンテンツデザイン演習",
    teacher: "稲舩 仁哉",
    room: "T313",
    style: 1,
  },
  {
    day: 2,
    period: 45,
    term: "A",
    consecutiveFlag: "",
    required: 0,
    minGrade: 2,
    maxGrade: 4,
    name: "都市・地域政策",
    teacher: "土屋 愛自",
    room: "マルチメディアホール",
    style: 0,
  },
  {
    day: 2,
    period: 45,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "システム工学",
    teacher: "森 健一郎",
    room: "T312",
    style: 0,
  },
  {
    day: 2,
    period: 3,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "データ処理基礎演習",
    teacher: "髙田 美樹",
    room: "T413",
    style: 0,
  },
  {
    day: 2,
    period: 3,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "プレゼンテーション技術Ｘ",
    teacher: "豊島 純子",
    room: "T414",
    style: 0,
  },
  {
    day: 2,
    period: 4,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "知的財産権",
    teacher: "加納 昌彦",
    room: "その他",
    style: 1,
  },
  {
    day: 2,
    period: 4,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "文化人類学",
    teacher: "思 沁夫",
    room: "T501,マルチメディアホール",
    style: 1,
  },
  {
    day: 2,
    period: 4,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "プレゼンテーション技術Y",
    teacher: "豊島 純子",
    room: "T414",
    style: 0,
  },
  {
    day: 2,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "デザイン理論（SD）",
    teacher: "秋元 淳",
    room: "T511",
    style: 0,
  },
  {
    day: 2,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 2,
    maxGrade: 4,
    name: "テクニカルライティングX",
    teacher: "大友 敬三",
    room: "T413",
    style: 0,
  },
  {
    day: 2,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 2,
    maxGrade: 4,
    name: "テクニカルライティングY",
    teacher: "浅川 英理子",
    room: "T414",
    style: 0,
  },
  {
    day: 2,
    period: 12,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "スマートマシンデザイン",
    teacher: "矢作 優知",
    room: "T413",
    style: 0,
  },
  {
    day: 2,
    period: 12,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "メカトロニクス",
    teacher: "伊藤 文臣",
    room: "T501",
    style: 0,
  },
  {
    day: 2,
    period: 2,
    term: "C",
    consecutiveFlag: "金2",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "工科系力学基礎",
    teacher: "五嶋 裕之",
    room: "T411,T412",
    style: 0,
  },
  {
    day: 2,
    period: 34,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "プロモーション映像制作",
    teacher: "新井 風愉",
    room: "SDスタジオルーム,情報教室1",
    style: 0,
  },
  {
    day: 2,
    period: 12,
    term: "D",
    consecutiveFlag: "",
    required: 0,
    minGrade: 2,
    maxGrade: 4,
    name: "サステナブルデザイン",
    teacher: "中野 淳太",
    room: "T413",
    style: 0,
  },
  {
    day: 2,
    period: 2,
    term: "D",
    consecutiveFlag: "木2",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "情報システムデザイン",
    teacher: "藤井 新吾",
    room: "T412",
    style: 0,
  },
  {
    day: 2,
    period: 2,
    term: "D",
    consecutiveFlag: "金2",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "エレクトロニクス基礎",
    teacher: "岩月 正見",
    room: "T411",
    style: 0,
  },
  {
    day: 2,
    period: 45,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "デザイン・バックキャスティング",
    teacher: "松山 祥樹",
    room: "SDスタジオルーム",
    style: 0,
  },
  {
    day: 3,
    period: 1,
    term: "AB",
    consecutiveFlag: "",
    required: 2,
    minGrade: 2,
    maxGrade: 4,
    name: "マネジメント基礎論",
    teacher: "姜 理惠",
    room: "T511",
    style: 0,
  },
  {
    day: 3,
    period: 12,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "基礎デザイン制作Y",
    teacher: "土屋 雅人",
    room: "SDスタジオ",
    style: 0,
  },
  {
    day: 3,
    period: 2,
    term: "AB",
    consecutiveFlag: "",
    required: 2,
    minGrade: 2,
    maxGrade: 4,
    name: "テクノロジー基礎論",
    teacher: "山田 泰之",
    room: "T511",
    style: 0,
  },
  {
    day: 3,
    period: 2,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "データサイエンス",
    teacher: "野々部 宏司",
    room: "T312",
    style: 0,
  },
  {
    day: 3,
    period: 3,
    term: "B",
    consecutiveFlag: "木3",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "デザインケーススタディ",
    teacher: "土屋 雅人",
    room: "都市スタジオ",
    style: 0,
  },
  {
    day: 3,
    period: 5,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "デザイン文化論",
    teacher: "辻村 亮子",
    room: "T511",
    style: 0,
  },
  {
    day: 3,
    period: 5,
    term: "AB",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "現代企業論",
    teacher: "境 新一",
    room: "T411",
    style: 0,
  },
  {
    day: 3,
    period: 5,
    term: "AB",
    consecutiveFlag: "月2",
    required: 2,
    minGrade: 3,
    maxGrade: 3,
    name: "ゼミナール1",
    teacher: "SEONG YOUNG AH",
    room: "T312他",
    style: 0,
  },
  {
    day: 3,
    period: 4,
    term: "A",
    consecutiveFlag: "金3",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "システムデザイン入門",
    teacher: "土屋 雅人",
    room: "T511",
    style: 0,
  },
  {
    day: 3,
    period: 12,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "プログラミング基礎演習X",
    teacher: "髙田 美樹",
    room: "T313",
    style: 0,
  },
  {
    day: 3,
    period: 34,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "メカニカルデザイン",
    teacher: "山田 泰之",
    room: "T511",
    style: 0,
  },
  {
    day: 3,
    period: 34,
    term: "B",
    consecutiveFlag: "",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "線形代数学Y",
    teacher: "井沼 学",
    room: "T313",
    style: 0,
  },
  {
    day: 3,
    period: 34,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "素材と機能のデザイン",
    teacher: "堀井 辰衛",
    room: "T414",
    style: 0,
  },
  {
    day: 3,
    period: 1,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "マーケティング",
    teacher: "林 奈生子",
    room: "その他",
    style: 1,
  },
  {
    day: 3,
    period: 2,
    term: "CD",
    consecutiveFlag: "",
    required: 2,
    minGrade: 2,
    maxGrade: 4,
    name: "クリエーション基礎論",
    teacher: "土屋 雅人",
    room: "SDスタジオ",
    style: 0,
  },
  {
    day: 3,
    period: 2,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "図学設計基礎演習Y",
    teacher: "石橋 忠人",
    room: "T311,情報教室1,情報教室2",
    style: 0,
  },
  {
    day: 3,
    period: 3,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "図学設計基礎演習X",
    teacher: "石橋 忠人",
    room: "T311,情報教室1,情報教室2",
    style: 0,
  },
  {
    day: 3,
    period: 34,
    term: "CD",
    consecutiveFlag: "月34",
    required: 2,
    minGrade: 3,
    maxGrade: 3,
    name: "プロジェクト実習・制作2",
    teacher: "SEONG YOUNG AH",
    room: ",SDスタジオ他",
    style: 0,
  },
  {
    day: 3,
    period: 4,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "認知科学（都市・SD）",
    teacher: "SEONG YOUNG AH",
    room: "その他",
    style: 1,
  },
  {
    day: 3,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "色彩論",
    teacher: "大高 知子",
    room: "マルチメディアホール",
    style: 0,
  },
  {
    day: 3,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "法学概論",
    teacher: "蓼沼 佳孝",
    room: "T312",
    style: 0,
  },
  {
    day: 3,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "デザイン思想史概論",
    teacher: "高橋 美礼",
    room: "その他",
    style: 1,
  },
  {
    day: 3,
    period: 6,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 3,
    maxGrade: 4,
    name: "デザインフォーラム",
    teacher: "下吹越 武人",
    room: "マルチメディアホール",
    style: 0,
  },
  {
    day: 3,
    period: 12,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "プロジェクトマネジメント（SD）",
    teacher: "川村 武也",
    room: "T313",
    style: 0,
  },
  {
    day: 3,
    period: 34,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "インタフェースデザイン",
    teacher: "土屋 雅人",
    room: "T411",
    style: 0,
  },
  {
    day: 3,
    period: 34,
    term: "C",
    consecutiveFlag: "",
    required: 0,
    minGrade: 3,
    maxGrade: 4,
    name: "タウンマネジメント",
    teacher: "土屋 愛自",
    room: "T412",
    style: 0,
  },
  {
    day: 3,
    period: 34,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "Webアプリプログラミング演習",
    teacher: "馬場 祐人",
    room: "T313",
    style: 0,
  },
  {
    day: 4,
    period: 12,
    term: "AB",
    consecutiveFlag: "",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "デザインスタジオ1（SD）",
    teacher: "大西 景太",
    room: "SDスタジオ他",
    style: 0,
  },
  {
    day: 4,
    period: 2,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "数理統計学（建築・SD）",
    teacher: "牧野 倫子",
    room: "T411",
    style: 0,
  },
  {
    day: 4,
    period: 3,
    term: "A",
    consecutiveFlag: "水3",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "デザインケーススタディ",
    teacher: "土屋 雅人",
    room: "T511",
    style: 0,
  },
  {
    day: 4,
    period: 3,
    term: "AB",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "イタリア語・イタリア文化（SD）",
    teacher: "MICHELE VERGOLANI",
    room: "T414",
    style: 0,
  },
  {
    day: 4,
    period: 34,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "プロダクトデザイン演習",
    teacher: "安積 伸",
    room: "SDスタジオ",
    style: 0,
  },
  {
    day: 4,
    period: 45,
    term: "A",
    consecutiveFlag: "月45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語1",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 4,
    period: 56,
    term: "A",
    consecutiveFlag: "月56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語1（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 4,
    period: 45,
    term: "B",
    consecutiveFlag: "月45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語2",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 4,
    period: 45,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "サービスUXデザイン",
    teacher: "平田 昌大",
    room: "都市スタジオ",
    style: 0,
  },
  {
    day: 4,
    period: 56,
    term: "B",
    consecutiveFlag: "月56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語2（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 4,
    period: 1,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "生態学概論",
    teacher: "山田 由美",
    room: "T411",
    style: 0,
  },
  {
    day: 4,
    period: 1,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "品質マネジメント",
    teacher: "池庄司 雅臣",
    room: "マルチメディアホール",
    style: 0,
  },
  {
    day: 4,
    period: 2,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "哲学",
    teacher: "大西 悟",
    room: "T411",
    style: 0,
  },
  {
    day: 4,
    period: 3,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "エンジニアリングデザインの基礎",
    teacher: "藤本 貴子",
    room: "T412",
    style: 0,
  },
  {
    day: 4,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "コストマネジメント",
    teacher: "北山 一真",
    room: "T312",
    style: 0,
  },
  {
    day: 4,
    period: 12,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "アントレプレナーシップ",
    teacher: "姜 理惠",
    room: "T313",
    style: 0,
  },
  {
    day: 4,
    period: 12,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "グラフィックデザイン演習(X)",
    teacher: "大西 景太",
    room: "SDスタジオ,都市スタジオ",
    style: 0,
  },
  {
    day: 4,
    period: 12,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "グラフィックデザイン演習(Y)",
    teacher: "大西 景太",
    room: "SDスタジオ,都市スタジオ",
    style: 0,
  },
  {
    day: 4,
    period: 34,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "コンテンツプログラミング演習X",
    teacher: "佐藤 由子",
    room: "情報教室1",
    style: 0,
  },
  {
    day: 4,
    period: 34,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "コンテンツプログラミング演習Y",
    teacher: "馬場 祐人",
    room: "T311",
    style: 0,
  },
  {
    day: 4,
    period: 34,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "材料と構造のデザイン",
    teacher: "武居 秀樹",
    room: "T313",
    style: 0,
  },
  {
    day: 4,
    period: 45,
    term: "C",
    consecutiveFlag: "月45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語3",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 4,
    period: 56,
    term: "C",
    consecutiveFlag: "月56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語3（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 4,
    period: 12,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "デジタルデザイン演習X",
    teacher: "土屋 雅人",
    room: "情報教室1",
    style: 0,
  },
  {
    day: 4,
    period: 12,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "デジタルデザイン演習Y",
    teacher: "土屋 雅人",
    room: "情報教室2",
    style: 0,
  },
  {
    day: 4,
    period: 12,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "メカトロニクス演習",
    teacher: "岩月 正見",
    room: "T313",
    style: 0,
  },
  {
    day: 4,
    period: 2,
    term: "D",
    consecutiveFlag: "火2",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "情報システムデザイン",
    teacher: "藤井 新吾",
    room: "T412",
    style: 0,
  },
  {
    day: 4,
    period: 34,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "AIプログラミング",
    teacher: "我妻 幸長",
    room: "その他",
    style: 1,
  },
  {
    day: 4,
    period: 34,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "メカニカルデザイン演習",
    teacher: "山田 泰之",
    room: "SDスタジオ",
    style: 0,
  },
  {
    day: 4,
    period: 45,
    term: "D",
    consecutiveFlag: "月45",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語4",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 4,
    period: 56,
    term: "D",
    consecutiveFlag: "月56",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "英語4（補講）",
    teacher: "デザイン工学部担当教員",
    room: "その他 ※1",
    style: 0,
  },
  {
    day: 5,
    period: 23,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "マーケティング演習",
    teacher: "野々部 宏司",
    room: "T412",
    style: 0,
  },
  {
    day: 5,
    period: 5,
    term: "AB",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "プロダクトデザイン理論",
    teacher: "安積 伸",
    room: "T313",
    style: 0,
  },
  {
    day: 5,
    period: 12,
    term: "A",
    consecutiveFlag: "",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "微分積分学X",
    teacher: "倉田 俊彦",
    room: "T312",
    style: 0,
  },
  {
    day: 5,
    period: 3,
    term: "A",
    consecutiveFlag: "水4",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "システムデザイン入門",
    teacher: "土屋 雅人",
    room: "T411",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "A",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "ゲームプログラミング",
    teacher: "岩月 正見",
    room: "T414",
    style: 0,
  },
  {
    day: 5,
    period: 12,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "デジタルエンジニアリング",
    teacher: "水野 操",
    room: "T311",
    style: 0,
  },
  {
    day: 5,
    period: 12,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "デザイン思考基礎演習",
    teacher: "安積 伸",
    room: "建築スタジオ,SDスタジオ",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "プログラミング基礎演習Y",
    teacher: "青山 翔吾",
    room: "T314",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "B",
    consecutiveFlag: "",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "線形代数学X",
    teacher: "倉田 俊彦",
    room: "T501",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "アフェクティブデザイン",
    teacher: "SEONG YOUNG AH",
    room: "T313",
    style: 0,
  },
  {
    day: 5,
    period: 12,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 3,
    maxGrade: 4,
    name: "公共空間デザイン及演習",
    teacher: "福井 恒明",
    room: "都市スタジオルーム",
    style: 0,
  },
  {
    day: 5,
    period: 3,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "開発と国際協力",
    teacher: "浅川 英理子",
    room: "T411",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "CD",
    consecutiveFlag: "",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "デザインスタジオ2（SD）",
    teacher: "安積 伸",
    room: "SDスタジオ他",
    style: 0,
  },
  {
    day: 5,
    period: 4,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "公共経営戦略",
    teacher: "竹末 直樹",
    room: "T411",
    style: 0,
  },
  {
    day: 5,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "エコノミクス",
    teacher: "李 江南",
    room: "T511",
    style: 0,
  },
  {
    day: 5,
    period: 5,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 2,
    maxGrade: 4,
    name: "Design Basics in English",
    teacher: "ディン ボリバン",
    room: "T206",
    style: 0,
  },
  {
    day: 5,
    period: 6,
    term: "CD",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "文化と文明",
    teacher: "小林 信也",
    room: "マルチメディアホール",
    style: 0,
  },
  {
    day: 5,
    period: 12,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "インクルーシブデザイン",
    teacher: "安積 伸",
    room: "SDスタジオ",
    style: 0,
  },
  {
    day: 5,
    period: 2,
    term: "C",
    consecutiveFlag: "火2",
    required: 2,
    minGrade: 1,
    maxGrade: 4,
    name: "工科系力学基礎",
    teacher: "五嶋 裕之",
    room: "T411,T412",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "C",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "Iotプログラミング",
    teacher: "岩月 正見",
    room: "T312",
    style: 0,
  },
  {
    day: 5,
    period: 2,
    term: "D",
    consecutiveFlag: "火2",
    required: 1,
    minGrade: 1,
    maxGrade: 4,
    name: "エレクトロニクス基礎",
    teacher: "岩月 正見",
    room: "T411",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 3,
    maxGrade: 4,
    name: "熱と流れのデザイン",
    teacher: "坂間 清子",
    room: "T313",
    style: 0,
  },
  {
    day: 5,
    period: 34,
    term: "D",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "オペレーションズリサーチ（SD）",
    teacher: "野々部 宏司",
    room: "T413",
    style: 0,
  },
  {
    day: 6,
    period: 1,
    term: "AB",
    consecutiveFlag: "",
    required: 0,
    minGrade: 1,
    maxGrade: 4,
    name: "デザイン工学概論",
    teacher: "南後 由和",
    room: "その他",
    style: 1,
  },
  {
    day: 6,
    period: 12,
    term: "B",
    consecutiveFlag: "",
    required: 1,
    minGrade: 2,
    maxGrade: 4,
    name: "モデリングとシミュレーション",
    teacher: "日比野 浩典",
    room: "その他",
    style: 1,
  },
];

export {SD};


